config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :phone_number, length: { is: 10 }
  CATEGORY = ['chinese', 'italian', 'japanese', 'french', 'belgian']
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, presence: true
  validates :content, presence: true
  RANGE = (0..5)
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: RANGE }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(strong_params)
    if @restaurant.save
      # when it saves -> go to the restaurants show page
      redirect_to restaurant_path(@restaurant)
    else
      # when it doesnt save -> show the form again
      render 'new', status: :unprocessable_entity # throws a 422 (for Turbo)
    end
  end

  private

  def strong_params
    params.require(:restaurant).permit(:name, :address,:phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(strong_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render '../views/restaurants/show.html.erb', status: :unprocessable_entity # throws a 422 (for Turbo)
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def strong_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/restaurants/_banner.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path("#{restaurant.category}.jpg")%>)">
  <%= restaurant.category %>
</div>

app/views/restaurants/index.html.erb
<div class="container d-flex justify-content-between align-items-center">
  <h1>Restaurants</h1>
  <%= link_to new_restaurant_path do %>
    <i class="fa-solid fa-plus"></i>
  <% end %>
</div>
<div class="cards mt-3">
  <% @restaurants.each do |restaurant| %>
    <%= link_to restaurant_path(restaurant) do  %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
        <%=  restaurant.name%>
      </div>
    <% end %>
  <% end %>
</div>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORY %>
  <%= f.submit class: 'btn btn-success' %>
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurant Page</h1>
<div class="col-8">
  <%= render "restaurants/banner", restaurant: @restaurant %>
  <div class="container mt-3">
    <h1><%= @restaurant.name %></h1>
    <hr>
    <h4><%= @restaurant.address %></h4>
    <h5>Contack us: <%= @restaurant.phone_number %></h5>
    <hr>
    <h3>Reviews</h3>
    <div class="reviews">
      <% if @restaurant.reviews.any? %>
        <% @restaurant.reviews.each do |review|%>
          <div class="row justify-content-between align-items-center">
            <div class="col-8 flex-grow-1">
              <strong><%= review.content %></strong>
            </div>
            <div class="col-3 d-flex justify-content-end">
              <% review.rating.times do %>
                <i class="fa-solid fa-heart d-flex"></i>
              <% end %>
            </div>
            <div class="col-1">
              <%= link_to review_path(review), data: { turbo_method: :delete, turbo_confirm: "are you sure?" } do %>
                <i class="fa-solid fa-trash"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <hr>
    <p><%= link_to "Back", restaurants_path %></p>
  </div>
</div>
<div class="container shadow col-4">
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <div class="star-rating">
      <%#= f.collection_radio_buttons :rating, [[1], [2], [3], [4], [5]], :first, :last do |b| %>
        <%#= b.radio_button%>
        <%# end %>
        <input type="radio" name="review[rating]" value="1" />
        <input type="radio" name="review[rating]" value="2" />
        <input type="radio" name="review[rating]" value="3" checked />
        <input type="radio" name="review[rating]" value="4" />
        <input type="radio" name="review[rating]" value="5" />
      </div>
      <%= f.submit :submit, class: "btn btn-secondary mt-3"%>
    <% end %>
  </div>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: 0..5%>
  <%= f.submit :submit %>
<% end %>